name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8.0.x ]
    name: check and assemble - jvm:${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v2
        env:
          GPR_AUTH_TOKEN: ${{secrets.GPR_AUTH_TOKEN}}
        with:
          arguments: clean check assemble
